name:                lambda-toy
version:             1.0.0.0
#synopsis:
#description:
homepage:            https://github.com/inventor02/lambda-toy#readme
license:             ISC
author:              George Peppard
maintainer:          gjp1g21@soton.ac.uk
copyright:           2023 George Peppard
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - array

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-matches
- -Wno-missing-export-lists
- -Wno-incomplete-patterns

library:
  source-dirs: src
  build-tools:
  - alex
  - happy

executables:
  lambda-toy-cli:
    source-dirs:      cli
    main:             Main.hs
    dependencies:
    - lambda-toy
  lambda-toy-int:
    source-dirs:      interactive
    main:             Main.hs
    dependencies:
    - lambda-toy
